dist: trusty
language: java
sudo: false
jdk:
- oraclejdk11
before_install:
- export TZ=Brazil/East
deploy:
  provider: heroku
  app: financial-java-api
  api_key:
    secure: nq6ct2w3sVr6aHCmHUlv0VCVhjzQweqAFGuqW05puEAri3W6+XygvQ+YTnbS7VNO97etk/EZwzCZk8YVJnDpwi6iQ2F3vPxJhxMw4SbVnCuKJZXPG7NPNj/+NCpVWAQDZ5QHln3V+E+uuc8rhmlQriFnne3wbihhvVDDWO5LkKm279Iq6tnxbJR5u9Mp8l0bT13Oa+WaTq/XE37qhiwE/jilwccUjvSYceBFUAXi3JhlCa1j7p29woLuEtFCy4x+hCbxVkZgyRWWb1+dFTd3+n0R6qxsJEX8Ppgoe/xWQtc5Ucpl3InCocDzjD1rvf7QbvUL+jnKMLlAdd7MGTirgx3oHql5shlh5QfzcBshJR9BgQQtwcGdCJAiM4xx6Sj2tKLjkO+1e8r/pQcV/GtiX2E0Um1xA0hCK+x9oOIqgSeyPlnr/bAIIDECr3AKHmMGRkKvR7K2ZtYyCB1Z3gEOLPw200/KkYqsJ4r65hyu4b7qmEs3BhWXbZVPbhLaspMlgiKiEcysecg4gPFZ0cSsubrHtqVAPLxtXMhDpi6VkpsOGYJPIZnnODv4DETGlygmiWO1miTqZECchJlxrjX5MvKlkX1lu8dXVPgX4VgNCPOOgEjNuFm8kTw95vZRhDXGXg2fiCUOE23yO/beTC9kywy2e/959FaIshsz2O7GuNs=
